// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Demo.Infrastructure.Repositories.Entities
{

    // Animal
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Animal
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public int Legs { get; set; } // Legs
        public int FamilyId { get; set; } // FamilyId

        // Reverse navigation

        /// <summary>
        /// Child Foods (Many-to-Many) mapped by table [AnimalEats]
        /// </summary>
        public System.Collections.Generic.ICollection<Food> Foods { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Family pointed by [Animal].([FamilyId]) (FK_Animal_Family)
        /// </summary>
        public Family Family { get; set; } // FK_Animal_Family

        public Animal()
        {
            Foods = new System.Collections.Generic.List<Food>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
