// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Demo.Infrastructure.Repositories.Entities
{

    public partial class DemoContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<DemoContext>
    {
        public DemoContext Create()
        {
            return new DemoContext(ConnectionString);
        }
    }
}
// </auto-generated>
