// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Demo.Infrastructure.Repositories.Entities
{

    // Family
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    internal class FamilyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Family>
    {
        public FamilyConfiguration()
            : this("dbo")
        {
        }

        public FamilyConfiguration(string schema)
        {
            ToTable("Family", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            HasMany(t => t.Foods).WithMany(t => t.Families).Map(m =>
            {
                m.ToTable("AnimalCanEats", "dbo");
                m.MapLeftKey("FamilyId");
                m.MapRightKey("FoodId");
            });
        }
    }

}
// </auto-generated>
