// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Demo.Infrastructure.Repositories.Entities
{

    // Family
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Family
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Animals where [Animal].[FamilyId] point to this entity (FK_Animal_Family)
        /// </summary>
        public System.Collections.Generic.ICollection<Animal> Animals { get; set; } // Animal.FK_Animal_Family
        /// <summary>
        /// Child Foods (Many-to-Many) mapped by table [AnimalCanEats]
        /// </summary>
        public System.Collections.Generic.ICollection<Food> Foods { get; set; } // Many to many mapping

        public Family()
        {
            Animals = new System.Collections.Generic.List<Animal>();
            Foods = new System.Collections.Generic.List<Food>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
