// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Demo.Infrastructure.Repositories.Entities
{

    // Food
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Food
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Animals (Many-to-Many) mapped by table [AnimalEats]
        /// </summary>
        public System.Collections.Generic.ICollection<Animal> Animals { get; set; } // Many to many mapping
        /// <summary>
        /// Child Families (Many-to-Many) mapped by table [AnimalCanEats]
        /// </summary>
        public System.Collections.Generic.ICollection<Family> Families { get; set; } // Many to many mapping

        public Food()
        {
            Families = new System.Collections.Generic.List<Family>();
            Animals = new System.Collections.Generic.List<Animal>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
